-- Migration: add worker_id to users and create app_config table
-- Date: 2026-01-19

ALTER TABLE users
    ADD COLUMN IF NOT EXISTS worker_id VARCHAR(64);

CREATE TABLE IF NOT EXISTS app_config (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(200) NOT NULL,
    version VARCHAR(64) NOT NULL,
    description VARCHAR(500),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_by VARCHAR(150)
);

INSERT INTO app_config (name, version, description)
SELECT 'DUT Management API', '1.0.0', 'Wireless Test Data Analysis Platform'
WHERE NOT EXISTS (SELECT 1 FROM app_config);
