"""add_email_last_login_created_at_to_users

Revision ID: 1731571e4f3c
Revises: a629fcf9f322
Create Date: 2025-12-01 21:47:50.980368

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1731571e4f3c'
down_revision = 'a629fcf9f322'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # These columns already exist in the initial migration (bf71b01cfcf0)
    # No operation needed
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # No operation needed
    pass
    # ### end Alembic commands ###
