"""add_email_last_login_created_at_to_users

Revision ID: 1731571e4f3c
Revises: a629fcf9f322
Create Date: 2025-12-01 21:47:50.980368

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1731571e4f3c'
down_revision = 'a629fcf9f322'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Constraints already exist, only adding new columns
    op.add_column('users', sa.Column('email', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('last_login', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('created_at', sa.DateTime(), nullable=False, server_default=sa.func.now()))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'created_at')
    op.drop_column('users', 'last_login')
    op.drop_column('users', 'email')
    # ### end Alembic commands ###
