"""add_top_product_tables

Revision ID: 6356ccd2f4ca
Revises: 8612ad6ea0a5
Create Date: 2025-12-12 14:14:18.791861

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '6356ccd2f4ca'
down_revision = '8612ad6ea0a5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('top_products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dut_isn', sa.String(), nullable=False),
    sa.Column('dut_id', sa.Integer(), nullable=True),
    sa.Column('site_name', sa.String(), nullable=True),
    sa.Column('project_name', sa.String(), nullable=True),
    sa.Column('model_name', sa.String(), nullable=True),
    sa.Column('station_name', sa.String(), nullable=False),
    sa.Column('device_name', sa.String(), nullable=True),
    sa.Column('test_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('test_duration', sa.Float(), nullable=True),
    sa.Column('pass_count', sa.Integer(), nullable=True),
    sa.Column('fail_count', sa.Integer(), nullable=True),
    sa.Column('retest_count', sa.Integer(), nullable=True),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_top_products_dut_isn'), 'top_products', ['dut_isn'], unique=False)
    op.create_index(op.f('ix_top_products_id'), 'top_products', ['id'], unique=False)
    op.create_index(op.f('ix_top_products_station_name'), 'top_products', ['station_name'], unique=False)
    op.create_table('top_product_measurements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('top_product_id', sa.Integer(), nullable=False),
    sa.Column('test_item', sa.String(), nullable=False),
    sa.Column('usl', sa.Float(), nullable=True),
    sa.Column('lsl', sa.Float(), nullable=True),
    sa.Column('target_value', sa.Float(), nullable=True),
    sa.Column('actual_value', sa.Float(), nullable=True),
    sa.Column('deviation', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['top_product_id'], ['top_products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_top_product_measurements_id'), 'top_product_measurements', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_top_product_measurements_id'), table_name='top_product_measurements')
    op.drop_table('top_product_measurements')
    op.drop_index(op.f('ix_top_products_station_name'), table_name='top_products')
    op.drop_index(op.f('ix_top_products_id'), table_name='top_products')
    op.drop_index(op.f('ix_top_products_dut_isn'), table_name='top_products')
    op.drop_table('top_products')
    # ### end Alembic commands ###
