"""add_updated_at_to_users

Revision ID: 8612ad6ea0a5
Revises: 1731571e4f3c
Create Date: 2025-12-01 21:54:29.349655

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8612ad6ea0a5'
down_revision = '1731571e4f3c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Constraints already exist, only adding updated_at column
    op.add_column('users', sa.Column('updated_at', sa.DateTime(), nullable=False, server_default=sa.func.now()))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'updated_at')
    # ### end Alembic commands ###
    # ### end Alembic commands ###
