"""add_updated_at_to_users

Revision ID: 8612ad6ea0a5
Revises: 1731571e4f3c
Create Date: 2025-12-01 21:54:29.349655

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8612ad6ea0a5'
down_revision = '1731571e4f3c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # updated_at column already exists in the initial migration (bf71b01cfcf0)
    # No operation needed
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # No operation needed
    pass
    # ### end Alembic commands ###
