"""Initial migration - create all tables

Revision ID: bf71b01cfcf0
Revises:
Create Date: 2025-10-29 17:24:28.523443

"""

from alembic import op

# revision identifiers, used by Alembic.
revision = "bf71b01cfcf0"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint("uq_role_perm", "role_permissions", ["role_id", "perm_id"])
    op.create_unique_constraint("uq_user_role", "user_roles", ["user_id", "role_id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_user_role", "user_roles", type_="unique")
    op.drop_constraint("uq_role_perm", "role_permissions", type_="unique")
    # ### end Alembic commands ###
