"""add_is_ptb_admin_to_users

Revision ID: ce0545504c00
Revises: 6356ccd2f4ca
Create Date: 2025-12-15 08:38:20.407734

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ce0545504c00'
down_revision = '6356ccd2f4ca'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add is_ptb_admin column to track external PTB admin status
    op.add_column('users', sa.Column('is_ptb_admin', sa.Boolean(), nullable=False, server_default='false'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_ptb_admin')
    # ### end Alembic commands ###
